image: laserb/audio-keras-cpu

train:
    before_script:
        - mkdir bot_data
        - sox -n -r 16000 -b 16 "bot_data/test_instrumental.wav" synth 3 sine 500
        - sox -n -r 16000 -b 16 "bot_data/test_acapella.wav" synth 3 sine 700
        - sox -n -r 16000 -b 16 "bot_data/test_all.wav" synth 3 sine 500 sine 700

    script:
        - export EPOCHS="1"
        - export DATA="bot_data"
        - python3 ./acapellabot.py

analyse:
    before_script:
        - sox -n -r 16000 -b 16 "test.wav" synth 3 sine 500 sine 700
    script:
        - python3 ./analysis.py --analyse slices test.wav
